services:
    mdenet-tool-yamtl:
        image: yamtl-m2m:latest
        ports:
            - "8500:80"
        build:
          context: .
          dockerfile: static.yamtlgroovy/Dockerfile

    mdenet-tool-emf:
        image: mdenet-tool-emf:latest
        ports:
            - "8073:80"
        build:
          context: .
          dockerfile: static.emf/Dockerfile

    mdenet-test-activities:
        image: "nginx:1.25-alpine"
        ports:
            - "8083:80"
        volumes:
            - ./activities-config/nginx.conf:/etc/nginx/nginx.conf
            - ./activities-config/default.conf:/etc/nginx/conf.d/default.conf
            - ./activities:/usr/share/nginx/html
